name: Test Backend

on: [push]
  

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
      with:
        jestArgs: backend/todo.test.js
      
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017       
