name: Test Backend

on: [push]
  

jobs:
  install:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Start & Test backend
        uses: stefanoeb/jest-action@1.0.3
        with:
          working-directory: backend
          start: npm install && npm run test
      
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017       
