name: E2E on Chrome

on: [push]
  

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Server
        uses: cypress-io/github-action@v3
        with:
          working-directory: backend
          start: npm start
          wait-on: "http://localhost:3000/todo.html"

      - name: Cypress run
        run: npm run cypress:run
          
          
      - run: echo "PR number is $CYPRESS_PULL_REQUEST_ID"
      - run: echo "PR URL is $CYPRESS_PULL_REQUEST_URL"
      
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017        
        
        
