name: E2E on Chrome

on: [push]
  

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.6.6
      options: --user 1001
    strategy:
      matrix:
        # Run the steps below with the following versions of Node.js
        node-version: [18.x]

        
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start Server
        uses: cypress-io/github-action@v3
        with:
          working-directory: backend
          start: npm start
          

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with: 
          working-directory: todo
          start: npm run cypress:run
      
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017        
        
        
